// Generated by DLL Hijacking Generator

#include "winmm.h"

PVOID pfn_CloseDriver;
PVOID pfn_DefDriverProc;
PVOID pfn_DriverCallback;
PVOID pfn_DrvGetModuleHandle;
PVOID pfn_GetDriverModuleHandle;
PVOID pfn_OpenDriver;
PVOID pfn_PlaySound;
PVOID pfn_PlaySoundA;
PVOID pfn_PlaySoundW;
PVOID pfn_SendDriverMessage;
PVOID pfn_WOWAppExit;
PVOID pfn_auxGetDevCapsA;
PVOID pfn_auxGetDevCapsW;
PVOID pfn_auxGetNumDevs;
PVOID pfn_auxGetVolume;
PVOID pfn_auxOutMessage;
PVOID pfn_auxSetVolume;
PVOID pfn_joyConfigChanged;
PVOID pfn_joyGetDevCapsA;
PVOID pfn_joyGetDevCapsW;
PVOID pfn_joyGetNumDevs;
PVOID pfn_joyGetPos;
PVOID pfn_joyGetPosEx;
PVOID pfn_joyGetThreshold;
PVOID pfn_joyReleaseCapture;
PVOID pfn_joySetCapture;
PVOID pfn_joySetThreshold;
PVOID pfn_mciDriverNotify;
PVOID pfn_mciDriverYield;
PVOID pfn_mciExecute;
PVOID pfn_mciFreeCommandResource;
PVOID pfn_mciGetCreatorTask;
PVOID pfn_mciGetDeviceIDA;
PVOID pfn_mciGetDeviceIDFromElementIDA;
PVOID pfn_mciGetDeviceIDFromElementIDW;
PVOID pfn_mciGetDeviceIDW;
PVOID pfn_mciGetDriverData;
PVOID pfn_mciGetErrorStringA;
PVOID pfn_mciGetErrorStringW;
PVOID pfn_mciGetYieldProc;
PVOID pfn_mciLoadCommandResource;
PVOID pfn_mciSendCommandA;
PVOID pfn_mciSendCommandW;
PVOID pfn_mciSendStringA;
PVOID pfn_mciSendStringW;
PVOID pfn_mciSetDriverData;
PVOID pfn_mciSetYieldProc;
PVOID pfn_midiConnect;
PVOID pfn_midiDisconnect;
PVOID pfn_midiInAddBuffer;
PVOID pfn_midiInClose;
PVOID pfn_midiInGetDevCapsA;
PVOID pfn_midiInGetDevCapsW;
PVOID pfn_midiInGetErrorTextA;
PVOID pfn_midiInGetErrorTextW;
PVOID pfn_midiInGetID;
PVOID pfn_midiInGetNumDevs;
PVOID pfn_midiInMessage;
PVOID pfn_midiInOpen;
PVOID pfn_midiInPrepareHeader;
PVOID pfn_midiInReset;
PVOID pfn_midiInStart;
PVOID pfn_midiInStop;
PVOID pfn_midiInUnprepareHeader;
PVOID pfn_midiOutCacheDrumPatches;
PVOID pfn_midiOutCachePatches;
PVOID pfn_midiOutClose;
PVOID pfn_midiOutGetDevCapsA;
PVOID pfn_midiOutGetDevCapsW;
PVOID pfn_midiOutGetErrorTextA;
PVOID pfn_midiOutGetErrorTextW;
PVOID pfn_midiOutGetID;
PVOID pfn_midiOutGetNumDevs;
PVOID pfn_midiOutGetVolume;
PVOID pfn_midiOutLongMsg;
PVOID pfn_midiOutMessage;
PVOID pfn_midiOutOpen;
PVOID pfn_midiOutPrepareHeader;
PVOID pfn_midiOutReset;
PVOID pfn_midiOutSetVolume;
PVOID pfn_midiOutShortMsg;
PVOID pfn_midiOutUnprepareHeader;
PVOID pfn_midiStreamClose;
PVOID pfn_midiStreamOpen;
PVOID pfn_midiStreamOut;
PVOID pfn_midiStreamPause;
PVOID pfn_midiStreamPosition;
PVOID pfn_midiStreamProperty;
PVOID pfn_midiStreamRestart;
PVOID pfn_midiStreamStop;
PVOID pfn_mixerClose;
PVOID pfn_mixerGetControlDetailsA;
PVOID pfn_mixerGetControlDetailsW;
PVOID pfn_mixerGetDevCapsA;
PVOID pfn_mixerGetDevCapsW;
PVOID pfn_mixerGetID;
PVOID pfn_mixerGetLineControlsA;
PVOID pfn_mixerGetLineControlsW;
PVOID pfn_mixerGetLineInfoA;
PVOID pfn_mixerGetLineInfoW;
PVOID pfn_mixerGetNumDevs;
PVOID pfn_mixerMessage;
PVOID pfn_mixerOpen;
PVOID pfn_mixerSetControlDetails;
PVOID pfn_mmDrvInstall;
PVOID pfn_mmGetCurrentTask;
PVOID pfn_mmTaskBlock;
PVOID pfn_mmTaskCreate;
PVOID pfn_mmTaskSignal;
PVOID pfn_mmTaskYield;
PVOID pfn_mmioAdvance;
PVOID pfn_mmioAscend;
PVOID pfn_mmioClose;
PVOID pfn_mmioCreateChunk;
PVOID pfn_mmioDescend;
PVOID pfn_mmioFlush;
PVOID pfn_mmioGetInfo;
PVOID pfn_mmioInstallIOProcA;
PVOID pfn_mmioInstallIOProcW;
PVOID pfn_mmioOpenA;
PVOID pfn_mmioOpenW;
PVOID pfn_mmioRead;
PVOID pfn_mmioRenameA;
PVOID pfn_mmioRenameW;
PVOID pfn_mmioSeek;
PVOID pfn_mmioSendMessage;
PVOID pfn_mmioSetBuffer;
PVOID pfn_mmioSetInfo;
PVOID pfn_mmioStringToFOURCCA;
PVOID pfn_mmioStringToFOURCCW;
PVOID pfn_mmioWrite;
PVOID pfn_mmsystemGetVersion;
PVOID pfn_sndPlaySoundA;
PVOID pfn_sndPlaySoundW;
PVOID pfn_timeBeginPeriod;
PVOID pfn_timeEndPeriod;
PVOID pfn_timeGetDevCaps;
PVOID pfn_timeGetSystemTime;
PVOID pfn_timeGetTime;
PVOID pfn_timeKillEvent;
PVOID pfn_timeSetEvent;
PVOID pfn_waveInAddBuffer;
PVOID pfn_waveInClose;
PVOID pfn_waveInGetDevCapsA;
PVOID pfn_waveInGetDevCapsW;
PVOID pfn_waveInGetErrorTextA;
PVOID pfn_waveInGetErrorTextW;
PVOID pfn_waveInGetID;
PVOID pfn_waveInGetNumDevs;
PVOID pfn_waveInGetPosition;
PVOID pfn_waveInMessage;
PVOID pfn_waveInOpen;
PVOID pfn_waveInPrepareHeader;
PVOID pfn_waveInReset;
PVOID pfn_waveInStart;
PVOID pfn_waveInStop;
PVOID pfn_waveInUnprepareHeader;
PVOID pfn_waveOutBreakLoop;
PVOID pfn_waveOutClose;
PVOID pfn_waveOutGetDevCapsA;
PVOID pfn_waveOutGetDevCapsW;
PVOID pfn_waveOutGetErrorTextA;
PVOID pfn_waveOutGetErrorTextW;
PVOID pfn_waveOutGetID;
PVOID pfn_waveOutGetNumDevs;
PVOID pfn_waveOutGetPitch;
PVOID pfn_waveOutGetPlaybackRate;
PVOID pfn_waveOutGetPosition;
PVOID pfn_waveOutGetVolume;
PVOID pfn_waveOutMessage;
PVOID pfn_waveOutOpen;
PVOID pfn_waveOutPause;
PVOID pfn_waveOutPrepareHeader;
PVOID pfn_waveOutReset;
PVOID pfn_waveOutRestart;
PVOID pfn_waveOutSetPitch;
PVOID pfn_waveOutSetPlaybackRate;
PVOID pfn_waveOutSetVolume;
PVOID pfn_waveOutUnprepareHeader;
PVOID pfn_waveOutWrite;

static HMODULE g_OldModule = NULL;

VOID WINAPI Free()
{
    if (g_OldModule)
    {
        FreeLibrary(g_OldModule);
    }
}

BOOL WINAPI Load()
{
    TCHAR tzPath[MAX_PATH];

    GetSystemDirectory(tzPath, MAX_PATH);
    lstrcat(tzPath, TEXT("\\winmm.dll"));

    g_OldModule = LoadLibrary(tzPath);
    return g_OldModule != NULL;
}

PVOID WINAPI GetAddress(PCSTR pszProcName)
{
    FARPROC fpAddress = GetProcAddress(g_OldModule, pszProcName);
    if (fpAddress == NULL)
    {
        ExitProcess(-2);
    }
    return (PVOID)fpAddress;
}

BOOL WINAPI Init()
{
    pfn_CloseDriver = GetAddress("CloseDriver");
    pfn_DefDriverProc = GetAddress("DefDriverProc");
    pfn_DriverCallback = GetAddress("DriverCallback");
    pfn_DrvGetModuleHandle = GetAddress("DrvGetModuleHandle");
    pfn_GetDriverModuleHandle = GetAddress("GetDriverModuleHandle");
    pfn_OpenDriver = GetAddress("OpenDriver");
    pfn_PlaySound = GetAddress("PlaySound");
    pfn_PlaySoundA = GetAddress("PlaySoundA");
    pfn_PlaySoundW = GetAddress("PlaySoundW");
    pfn_SendDriverMessage = GetAddress("SendDriverMessage");
    pfn_WOWAppExit = GetAddress("WOWAppExit");
    pfn_auxGetDevCapsA = GetAddress("auxGetDevCapsA");
    pfn_auxGetDevCapsW = GetAddress("auxGetDevCapsW");
    pfn_auxGetNumDevs = GetAddress("auxGetNumDevs");
    pfn_auxGetVolume = GetAddress("auxGetVolume");
    pfn_auxOutMessage = GetAddress("auxOutMessage");
    pfn_auxSetVolume = GetAddress("auxSetVolume");
    pfn_joyConfigChanged = GetAddress("joyConfigChanged");
    pfn_joyGetDevCapsA = GetAddress("joyGetDevCapsA");
    pfn_joyGetDevCapsW = GetAddress("joyGetDevCapsW");
    pfn_joyGetNumDevs = GetAddress("joyGetNumDevs");
    pfn_joyGetPos = GetAddress("joyGetPos");
    pfn_joyGetPosEx = GetAddress("joyGetPosEx");
    pfn_joyGetThreshold = GetAddress("joyGetThreshold");
    pfn_joyReleaseCapture = GetAddress("joyReleaseCapture");
    pfn_joySetCapture = GetAddress("joySetCapture");
    pfn_joySetThreshold = GetAddress("joySetThreshold");
    pfn_mciDriverNotify = GetAddress("mciDriverNotify");
    pfn_mciDriverYield = GetAddress("mciDriverYield");
    pfn_mciExecute = GetAddress("mciExecute");
    pfn_mciFreeCommandResource = GetAddress("mciFreeCommandResource");
    pfn_mciGetCreatorTask = GetAddress("mciGetCreatorTask");
    pfn_mciGetDeviceIDA = GetAddress("mciGetDeviceIDA");
    pfn_mciGetDeviceIDFromElementIDA = GetAddress("mciGetDeviceIDFromElementIDA");
    pfn_mciGetDeviceIDFromElementIDW = GetAddress("mciGetDeviceIDFromElementIDW");
    pfn_mciGetDeviceIDW = GetAddress("mciGetDeviceIDW");
    pfn_mciGetDriverData = GetAddress("mciGetDriverData");
    pfn_mciGetErrorStringA = GetAddress("mciGetErrorStringA");
    pfn_mciGetErrorStringW = GetAddress("mciGetErrorStringW");
    pfn_mciGetYieldProc = GetAddress("mciGetYieldProc");
    pfn_mciLoadCommandResource = GetAddress("mciLoadCommandResource");
    pfn_mciSendCommandA = GetAddress("mciSendCommandA");
    pfn_mciSendCommandW = GetAddress("mciSendCommandW");
    pfn_mciSendStringA = GetAddress("mciSendStringA");
    pfn_mciSendStringW = GetAddress("mciSendStringW");
    pfn_mciSetDriverData = GetAddress("mciSetDriverData");
    pfn_mciSetYieldProc = GetAddress("mciSetYieldProc");
    pfn_midiConnect = GetAddress("midiConnect");
    pfn_midiDisconnect = GetAddress("midiDisconnect");
    pfn_midiInAddBuffer = GetAddress("midiInAddBuffer");
    pfn_midiInClose = GetAddress("midiInClose");
    pfn_midiInGetDevCapsA = GetAddress("midiInGetDevCapsA");
    pfn_midiInGetDevCapsW = GetAddress("midiInGetDevCapsW");
    pfn_midiInGetErrorTextA = GetAddress("midiInGetErrorTextA");
    pfn_midiInGetErrorTextW = GetAddress("midiInGetErrorTextW");
    pfn_midiInGetID = GetAddress("midiInGetID");
    pfn_midiInGetNumDevs = GetAddress("midiInGetNumDevs");
    pfn_midiInMessage = GetAddress("midiInMessage");
    pfn_midiInOpen = GetAddress("midiInOpen");
    pfn_midiInPrepareHeader = GetAddress("midiInPrepareHeader");
    pfn_midiInReset = GetAddress("midiInReset");
    pfn_midiInStart = GetAddress("midiInStart");
    pfn_midiInStop = GetAddress("midiInStop");
    pfn_midiInUnprepareHeader = GetAddress("midiInUnprepareHeader");
    pfn_midiOutCacheDrumPatches = GetAddress("midiOutCacheDrumPatches");
    pfn_midiOutCachePatches = GetAddress("midiOutCachePatches");
    pfn_midiOutClose = GetAddress("midiOutClose");
    pfn_midiOutGetDevCapsA = GetAddress("midiOutGetDevCapsA");
    pfn_midiOutGetDevCapsW = GetAddress("midiOutGetDevCapsW");
    pfn_midiOutGetErrorTextA = GetAddress("midiOutGetErrorTextA");
    pfn_midiOutGetErrorTextW = GetAddress("midiOutGetErrorTextW");
    pfn_midiOutGetID = GetAddress("midiOutGetID");
    pfn_midiOutGetNumDevs = GetAddress("midiOutGetNumDevs");
    pfn_midiOutGetVolume = GetAddress("midiOutGetVolume");
    pfn_midiOutLongMsg = GetAddress("midiOutLongMsg");
    pfn_midiOutMessage = GetAddress("midiOutMessage");
    pfn_midiOutOpen = GetAddress("midiOutOpen");
    pfn_midiOutPrepareHeader = GetAddress("midiOutPrepareHeader");
    pfn_midiOutReset = GetAddress("midiOutReset");
    pfn_midiOutSetVolume = GetAddress("midiOutSetVolume");
    pfn_midiOutShortMsg = GetAddress("midiOutShortMsg");
    pfn_midiOutUnprepareHeader = GetAddress("midiOutUnprepareHeader");
    pfn_midiStreamClose = GetAddress("midiStreamClose");
    pfn_midiStreamOpen = GetAddress("midiStreamOpen");
    pfn_midiStreamOut = GetAddress("midiStreamOut");
    pfn_midiStreamPause = GetAddress("midiStreamPause");
    pfn_midiStreamPosition = GetAddress("midiStreamPosition");
    pfn_midiStreamProperty = GetAddress("midiStreamProperty");
    pfn_midiStreamRestart = GetAddress("midiStreamRestart");
    pfn_midiStreamStop = GetAddress("midiStreamStop");
    pfn_mixerClose = GetAddress("mixerClose");
    pfn_mixerGetControlDetailsA = GetAddress("mixerGetControlDetailsA");
    pfn_mixerGetControlDetailsW = GetAddress("mixerGetControlDetailsW");
    pfn_mixerGetDevCapsA = GetAddress("mixerGetDevCapsA");
    pfn_mixerGetDevCapsW = GetAddress("mixerGetDevCapsW");
    pfn_mixerGetID = GetAddress("mixerGetID");
    pfn_mixerGetLineControlsA = GetAddress("mixerGetLineControlsA");
    pfn_mixerGetLineControlsW = GetAddress("mixerGetLineControlsW");
    pfn_mixerGetLineInfoA = GetAddress("mixerGetLineInfoA");
    pfn_mixerGetLineInfoW = GetAddress("mixerGetLineInfoW");
    pfn_mixerGetNumDevs = GetAddress("mixerGetNumDevs");
    pfn_mixerMessage = GetAddress("mixerMessage");
    pfn_mixerOpen = GetAddress("mixerOpen");
    pfn_mixerSetControlDetails = GetAddress("mixerSetControlDetails");
    pfn_mmDrvInstall = GetAddress("mmDrvInstall");
    pfn_mmGetCurrentTask = GetAddress("mmGetCurrentTask");
    pfn_mmTaskBlock = GetAddress("mmTaskBlock");
    pfn_mmTaskCreate = GetAddress("mmTaskCreate");
    pfn_mmTaskSignal = GetAddress("mmTaskSignal");
    pfn_mmTaskYield = GetAddress("mmTaskYield");
    pfn_mmioAdvance = GetAddress("mmioAdvance");
    pfn_mmioAscend = GetAddress("mmioAscend");
    pfn_mmioClose = GetAddress("mmioClose");
    pfn_mmioCreateChunk = GetAddress("mmioCreateChunk");
    pfn_mmioDescend = GetAddress("mmioDescend");
    pfn_mmioFlush = GetAddress("mmioFlush");
    pfn_mmioGetInfo = GetAddress("mmioGetInfo");
    pfn_mmioInstallIOProcA = GetAddress("mmioInstallIOProcA");
    pfn_mmioInstallIOProcW = GetAddress("mmioInstallIOProcW");
    pfn_mmioOpenA = GetAddress("mmioOpenA");
    pfn_mmioOpenW = GetAddress("mmioOpenW");
    pfn_mmioRead = GetAddress("mmioRead");
    pfn_mmioRenameA = GetAddress("mmioRenameA");
    pfn_mmioRenameW = GetAddress("mmioRenameW");
    pfn_mmioSeek = GetAddress("mmioSeek");
    pfn_mmioSendMessage = GetAddress("mmioSendMessage");
    pfn_mmioSetBuffer = GetAddress("mmioSetBuffer");
    pfn_mmioSetInfo = GetAddress("mmioSetInfo");
    pfn_mmioStringToFOURCCA = GetAddress("mmioStringToFOURCCA");
    pfn_mmioStringToFOURCCW = GetAddress("mmioStringToFOURCCW");
    pfn_mmioWrite = GetAddress("mmioWrite");
    pfn_mmsystemGetVersion = GetAddress("mmsystemGetVersion");
    pfn_sndPlaySoundA = GetAddress("sndPlaySoundA");
    pfn_sndPlaySoundW = GetAddress("sndPlaySoundW");
    pfn_timeBeginPeriod = GetAddress("timeBeginPeriod");
    pfn_timeEndPeriod = GetAddress("timeEndPeriod");
    pfn_timeGetDevCaps = GetAddress("timeGetDevCaps");
    pfn_timeGetSystemTime = GetAddress("timeGetSystemTime");
    pfn_timeGetTime = GetAddress("timeGetTime");
    pfn_timeKillEvent = GetAddress("timeKillEvent");
    pfn_timeSetEvent = GetAddress("timeSetEvent");
    pfn_waveInAddBuffer = GetAddress("waveInAddBuffer");
    pfn_waveInClose = GetAddress("waveInClose");
    pfn_waveInGetDevCapsA = GetAddress("waveInGetDevCapsA");
    pfn_waveInGetDevCapsW = GetAddress("waveInGetDevCapsW");
    pfn_waveInGetErrorTextA = GetAddress("waveInGetErrorTextA");
    pfn_waveInGetErrorTextW = GetAddress("waveInGetErrorTextW");
    pfn_waveInGetID = GetAddress("waveInGetID");
    pfn_waveInGetNumDevs = GetAddress("waveInGetNumDevs");
    pfn_waveInGetPosition = GetAddress("waveInGetPosition");
    pfn_waveInMessage = GetAddress("waveInMessage");
    pfn_waveInOpen = GetAddress("waveInOpen");
    pfn_waveInPrepareHeader = GetAddress("waveInPrepareHeader");
    pfn_waveInReset = GetAddress("waveInReset");
    pfn_waveInStart = GetAddress("waveInStart");
    pfn_waveInStop = GetAddress("waveInStop");
    pfn_waveInUnprepareHeader = GetAddress("waveInUnprepareHeader");
    pfn_waveOutBreakLoop = GetAddress("waveOutBreakLoop");
    pfn_waveOutClose = GetAddress("waveOutClose");
    pfn_waveOutGetDevCapsA = GetAddress("waveOutGetDevCapsA");
    pfn_waveOutGetDevCapsW = GetAddress("waveOutGetDevCapsW");
    pfn_waveOutGetErrorTextA = GetAddress("waveOutGetErrorTextA");
    pfn_waveOutGetErrorTextW = GetAddress("waveOutGetErrorTextW");
    pfn_waveOutGetID = GetAddress("waveOutGetID");
    pfn_waveOutGetNumDevs = GetAddress("waveOutGetNumDevs");
    pfn_waveOutGetPitch = GetAddress("waveOutGetPitch");
    pfn_waveOutGetPlaybackRate = GetAddress("waveOutGetPlaybackRate");
    pfn_waveOutGetPosition = GetAddress("waveOutGetPosition");
    pfn_waveOutGetVolume = GetAddress("waveOutGetVolume");
    pfn_waveOutMessage = GetAddress("waveOutMessage");
    pfn_waveOutOpen = GetAddress("waveOutOpen");
    pfn_waveOutPause = GetAddress("waveOutPause");
    pfn_waveOutPrepareHeader = GetAddress("waveOutPrepareHeader");
    pfn_waveOutReset = GetAddress("waveOutReset");
    pfn_waveOutRestart = GetAddress("waveOutRestart");
    pfn_waveOutSetPitch = GetAddress("waveOutSetPitch");
    pfn_waveOutSetPlaybackRate = GetAddress("waveOutSetPlaybackRate");
    pfn_waveOutSetVolume = GetAddress("waveOutSetVolume");
    pfn_waveOutUnprepareHeader = GetAddress("waveOutUnprepareHeader");
    pfn_waveOutWrite = GetAddress("waveOutWrite");
    return TRUE;
}

EXTERN_C __declspec(naked) void __cdecl proxyCloseDriver(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_CloseDriver;
#else
    asm volatile("jmp *%0" : : "r"(pfn_CloseDriver));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxyDefDriverProc(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_DefDriverProc;
#else
    asm volatile("jmp *%0" : : "r"(pfn_DefDriverProc));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxyDriverCallback(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_DriverCallback;
#else
    asm volatile("jmp *%0" : : "r"(pfn_DriverCallback));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxyDrvGetModuleHandle(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_DrvGetModuleHandle;
#else
    asm volatile("jmp *%0" : : "r"(pfn_DrvGetModuleHandle));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxyGetDriverModuleHandle(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_GetDriverModuleHandle;
#else
    asm volatile("jmp *%0" : : "r"(pfn_GetDriverModuleHandle));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxyOpenDriver(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_OpenDriver;
#else
    asm volatile("jmp *%0" : : "r"(pfn_OpenDriver));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxyPlaySound(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_PlaySound;
#else
    asm volatile("jmp *%0" : : "r"(pfn_PlaySound));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxyPlaySoundA(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_PlaySoundA;
#else
    asm volatile("jmp *%0" : : "r"(pfn_PlaySoundA));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxyPlaySoundW(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_PlaySoundW;
#else
    asm volatile("jmp *%0" : : "r"(pfn_PlaySoundW));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxySendDriverMessage(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_SendDriverMessage;
#else
    asm volatile("jmp *%0" : : "r"(pfn_SendDriverMessage));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxyWOWAppExit(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_WOWAppExit;
#else
    asm volatile("jmp *%0" : : "r"(pfn_WOWAppExit));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxyauxGetDevCapsA(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_auxGetDevCapsA;
#else
    asm volatile("jmp *%0" : : "r"(pfn_auxGetDevCapsA));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxyauxGetDevCapsW(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_auxGetDevCapsW;
#else
    asm volatile("jmp *%0" : : "r"(pfn_auxGetDevCapsW));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxyauxGetNumDevs(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_auxGetNumDevs;
#else
    asm volatile("jmp *%0" : : "r"(pfn_auxGetNumDevs));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxyauxGetVolume(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_auxGetVolume;
#else
    asm volatile("jmp *%0" : : "r"(pfn_auxGetVolume));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxyauxOutMessage(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_auxOutMessage;
#else
    asm volatile("jmp *%0" : : "r"(pfn_auxOutMessage));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxyauxSetVolume(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_auxSetVolume;
#else
    asm volatile("jmp *%0" : : "r"(pfn_auxSetVolume));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxyjoyConfigChanged(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_joyConfigChanged;
#else
    asm volatile("jmp *%0" : : "r"(pfn_joyConfigChanged));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxyjoyGetDevCapsA(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_joyGetDevCapsA;
#else
    asm volatile("jmp *%0" : : "r"(pfn_joyGetDevCapsA));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxyjoyGetDevCapsW(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_joyGetDevCapsW;
#else
    asm volatile("jmp *%0" : : "r"(pfn_joyGetDevCapsW));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxyjoyGetNumDevs(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_joyGetNumDevs;
#else
    asm volatile("jmp *%0" : : "r"(pfn_joyGetNumDevs));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxyjoyGetPos(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_joyGetPos;
#else
    asm volatile("jmp *%0" : : "r"(pfn_joyGetPos));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxyjoyGetPosEx(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_joyGetPosEx;
#else
    asm volatile("jmp *%0" : : "r"(pfn_joyGetPosEx));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxyjoyGetThreshold(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_joyGetThreshold;
#else
    asm volatile("jmp *%0" : : "r"(pfn_joyGetThreshold));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxyjoyReleaseCapture(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_joyReleaseCapture;
#else
    asm volatile("jmp *%0" : : "r"(pfn_joyReleaseCapture));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxyjoySetCapture(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_joySetCapture;
#else
    asm volatile("jmp *%0" : : "r"(pfn_joySetCapture));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxyjoySetThreshold(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_joySetThreshold;
#else
    asm volatile("jmp *%0" : : "r"(pfn_joySetThreshold));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymciDriverNotify(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mciDriverNotify;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mciDriverNotify));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymciDriverYield(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mciDriverYield;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mciDriverYield));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymciExecute(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mciExecute;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mciExecute));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymciFreeCommandResource(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mciFreeCommandResource;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mciFreeCommandResource));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymciGetCreatorTask(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mciGetCreatorTask;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mciGetCreatorTask));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymciGetDeviceIDA(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mciGetDeviceIDA;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mciGetDeviceIDA));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymciGetDeviceIDFromElementIDA(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mciGetDeviceIDFromElementIDA;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mciGetDeviceIDFromElementIDA));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymciGetDeviceIDFromElementIDW(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mciGetDeviceIDFromElementIDW;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mciGetDeviceIDFromElementIDW));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymciGetDeviceIDW(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mciGetDeviceIDW;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mciGetDeviceIDW));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymciGetDriverData(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mciGetDriverData;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mciGetDriverData));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymciGetErrorStringA(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mciGetErrorStringA;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mciGetErrorStringA));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymciGetErrorStringW(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mciGetErrorStringW;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mciGetErrorStringW));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymciGetYieldProc(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mciGetYieldProc;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mciGetYieldProc));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymciLoadCommandResource(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mciLoadCommandResource;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mciLoadCommandResource));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymciSendCommandA(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mciSendCommandA;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mciSendCommandA));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymciSendCommandW(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mciSendCommandW;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mciSendCommandW));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymciSendStringA(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mciSendStringA;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mciSendStringA));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymciSendStringW(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mciSendStringW;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mciSendStringW));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymciSetDriverData(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mciSetDriverData;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mciSetDriverData));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymciSetYieldProc(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mciSetYieldProc;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mciSetYieldProc));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymidiConnect(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_midiConnect;
#else
    asm volatile("jmp *%0" : : "r"(pfn_midiConnect));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymidiDisconnect(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_midiDisconnect;
#else
    asm volatile("jmp *%0" : : "r"(pfn_midiDisconnect));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymidiInAddBuffer(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_midiInAddBuffer;
#else
    asm volatile("jmp *%0" : : "r"(pfn_midiInAddBuffer));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymidiInClose(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_midiInClose;
#else
    asm volatile("jmp *%0" : : "r"(pfn_midiInClose));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymidiInGetDevCapsA(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_midiInGetDevCapsA;
#else
    asm volatile("jmp *%0" : : "r"(pfn_midiInGetDevCapsA));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymidiInGetDevCapsW(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_midiInGetDevCapsW;
#else
    asm volatile("jmp *%0" : : "r"(pfn_midiInGetDevCapsW));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymidiInGetErrorTextA(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_midiInGetErrorTextA;
#else
    asm volatile("jmp *%0" : : "r"(pfn_midiInGetErrorTextA));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymidiInGetErrorTextW(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_midiInGetErrorTextW;
#else
    asm volatile("jmp *%0" : : "r"(pfn_midiInGetErrorTextW));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymidiInGetID(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_midiInGetID;
#else
    asm volatile("jmp *%0" : : "r"(pfn_midiInGetID));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymidiInGetNumDevs(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_midiInGetNumDevs;
#else
    asm volatile("jmp *%0" : : "r"(pfn_midiInGetNumDevs));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymidiInMessage(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_midiInMessage;
#else
    asm volatile("jmp *%0" : : "r"(pfn_midiInMessage));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymidiInOpen(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_midiInOpen;
#else
    asm volatile("jmp *%0" : : "r"(pfn_midiInOpen));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymidiInPrepareHeader(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_midiInPrepareHeader;
#else
    asm volatile("jmp *%0" : : "r"(pfn_midiInPrepareHeader));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymidiInReset(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_midiInReset;
#else
    asm volatile("jmp *%0" : : "r"(pfn_midiInReset));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymidiInStart(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_midiInStart;
#else
    asm volatile("jmp *%0" : : "r"(pfn_midiInStart));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymidiInStop(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_midiInStop;
#else
    asm volatile("jmp *%0" : : "r"(pfn_midiInStop));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymidiInUnprepareHeader(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_midiInUnprepareHeader;
#else
    asm volatile("jmp *%0" : : "r"(pfn_midiInUnprepareHeader));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymidiOutCacheDrumPatches(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_midiOutCacheDrumPatches;
#else
    asm volatile("jmp *%0" : : "r"(pfn_midiOutCacheDrumPatches));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymidiOutCachePatches(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_midiOutCachePatches;
#else
    asm volatile("jmp *%0" : : "r"(pfn_midiOutCachePatches));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymidiOutClose(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_midiOutClose;
#else
    asm volatile("jmp *%0" : : "r"(pfn_midiOutClose));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymidiOutGetDevCapsA(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_midiOutGetDevCapsA;
#else
    asm volatile("jmp *%0" : : "r"(pfn_midiOutGetDevCapsA));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymidiOutGetDevCapsW(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_midiOutGetDevCapsW;
#else
    asm volatile("jmp *%0" : : "r"(pfn_midiOutGetDevCapsW));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymidiOutGetErrorTextA(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_midiOutGetErrorTextA;
#else
    asm volatile("jmp *%0" : : "r"(pfn_midiOutGetErrorTextA));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymidiOutGetErrorTextW(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_midiOutGetErrorTextW;
#else
    asm volatile("jmp *%0" : : "r"(pfn_midiOutGetErrorTextW));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymidiOutGetID(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_midiOutGetID;
#else
    asm volatile("jmp *%0" : : "r"(pfn_midiOutGetID));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymidiOutGetNumDevs(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_midiOutGetNumDevs;
#else
    asm volatile("jmp *%0" : : "r"(pfn_midiOutGetNumDevs));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymidiOutGetVolume(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_midiOutGetVolume;
#else
    asm volatile("jmp *%0" : : "r"(pfn_midiOutGetVolume));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymidiOutLongMsg(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_midiOutLongMsg;
#else
    asm volatile("jmp *%0" : : "r"(pfn_midiOutLongMsg));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymidiOutMessage(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_midiOutMessage;
#else
    asm volatile("jmp *%0" : : "r"(pfn_midiOutMessage));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymidiOutOpen(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_midiOutOpen;
#else
    asm volatile("jmp *%0" : : "r"(pfn_midiOutOpen));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymidiOutPrepareHeader(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_midiOutPrepareHeader;
#else
    asm volatile("jmp *%0" : : "r"(pfn_midiOutPrepareHeader));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymidiOutReset(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_midiOutReset;
#else
    asm volatile("jmp *%0" : : "r"(pfn_midiOutReset));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymidiOutSetVolume(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_midiOutSetVolume;
#else
    asm volatile("jmp *%0" : : "r"(pfn_midiOutSetVolume));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymidiOutShortMsg(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_midiOutShortMsg;
#else
    asm volatile("jmp *%0" : : "r"(pfn_midiOutShortMsg));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymidiOutUnprepareHeader(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_midiOutUnprepareHeader;
#else
    asm volatile("jmp *%0" : : "r"(pfn_midiOutUnprepareHeader));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymidiStreamClose(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_midiStreamClose;
#else
    asm volatile("jmp *%0" : : "r"(pfn_midiStreamClose));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymidiStreamOpen(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_midiStreamOpen;
#else
    asm volatile("jmp *%0" : : "r"(pfn_midiStreamOpen));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymidiStreamOut(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_midiStreamOut;
#else
    asm volatile("jmp *%0" : : "r"(pfn_midiStreamOut));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymidiStreamPause(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_midiStreamPause;
#else
    asm volatile("jmp *%0" : : "r"(pfn_midiStreamPause));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymidiStreamPosition(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_midiStreamPosition;
#else
    asm volatile("jmp *%0" : : "r"(pfn_midiStreamPosition));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymidiStreamProperty(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_midiStreamProperty;
#else
    asm volatile("jmp *%0" : : "r"(pfn_midiStreamProperty));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymidiStreamRestart(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_midiStreamRestart;
#else
    asm volatile("jmp *%0" : : "r"(pfn_midiStreamRestart));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymidiStreamStop(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_midiStreamStop;
#else
    asm volatile("jmp *%0" : : "r"(pfn_midiStreamStop));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymixerClose(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mixerClose;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mixerClose));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymixerGetControlDetailsA(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mixerGetControlDetailsA;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mixerGetControlDetailsA));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymixerGetControlDetailsW(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mixerGetControlDetailsW;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mixerGetControlDetailsW));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymixerGetDevCapsA(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mixerGetDevCapsA;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mixerGetDevCapsA));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymixerGetDevCapsW(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mixerGetDevCapsW;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mixerGetDevCapsW));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymixerGetID(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mixerGetID;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mixerGetID));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymixerGetLineControlsA(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mixerGetLineControlsA;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mixerGetLineControlsA));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymixerGetLineControlsW(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mixerGetLineControlsW;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mixerGetLineControlsW));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymixerGetLineInfoA(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mixerGetLineInfoA;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mixerGetLineInfoA));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymixerGetLineInfoW(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mixerGetLineInfoW;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mixerGetLineInfoW));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymixerGetNumDevs(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mixerGetNumDevs;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mixerGetNumDevs));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymixerMessage(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mixerMessage;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mixerMessage));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymixerOpen(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mixerOpen;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mixerOpen));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymixerSetControlDetails(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mixerSetControlDetails;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mixerSetControlDetails));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymmDrvInstall(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mmDrvInstall;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mmDrvInstall));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymmGetCurrentTask(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mmGetCurrentTask;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mmGetCurrentTask));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymmTaskBlock(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mmTaskBlock;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mmTaskBlock));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymmTaskCreate(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mmTaskCreate;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mmTaskCreate));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymmTaskSignal(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mmTaskSignal;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mmTaskSignal));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymmTaskYield(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mmTaskYield;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mmTaskYield));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymmioAdvance(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mmioAdvance;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mmioAdvance));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymmioAscend(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mmioAscend;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mmioAscend));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymmioClose(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mmioClose;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mmioClose));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymmioCreateChunk(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mmioCreateChunk;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mmioCreateChunk));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymmioDescend(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mmioDescend;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mmioDescend));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymmioFlush(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mmioFlush;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mmioFlush));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymmioGetInfo(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mmioGetInfo;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mmioGetInfo));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymmioInstallIOProcA(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mmioInstallIOProcA;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mmioInstallIOProcA));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymmioInstallIOProcW(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mmioInstallIOProcW;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mmioInstallIOProcW));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymmioOpenA(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mmioOpenA;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mmioOpenA));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymmioOpenW(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mmioOpenW;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mmioOpenW));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymmioRead(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mmioRead;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mmioRead));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymmioRenameA(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mmioRenameA;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mmioRenameA));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymmioRenameW(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mmioRenameW;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mmioRenameW));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymmioSeek(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mmioSeek;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mmioSeek));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymmioSendMessage(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mmioSendMessage;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mmioSendMessage));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymmioSetBuffer(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mmioSetBuffer;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mmioSetBuffer));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymmioSetInfo(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mmioSetInfo;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mmioSetInfo));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymmioStringToFOURCCA(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mmioStringToFOURCCA;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mmioStringToFOURCCA));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymmioStringToFOURCCW(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mmioStringToFOURCCW;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mmioStringToFOURCCW));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymmioWrite(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mmioWrite;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mmioWrite));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxymmsystemGetVersion(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_mmsystemGetVersion;
#else
    asm volatile("jmp *%0" : : "r"(pfn_mmsystemGetVersion));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxysndPlaySoundA(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_sndPlaySoundA;
#else
    asm volatile("jmp *%0" : : "r"(pfn_sndPlaySoundA));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxysndPlaySoundW(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_sndPlaySoundW;
#else
    asm volatile("jmp *%0" : : "r"(pfn_sndPlaySoundW));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxytimeBeginPeriod(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_timeBeginPeriod;
#else
    asm volatile("jmp *%0" : : "r"(pfn_timeBeginPeriod));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxytimeEndPeriod(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_timeEndPeriod;
#else
    asm volatile("jmp *%0" : : "r"(pfn_timeEndPeriod));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxytimeGetDevCaps(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_timeGetDevCaps;
#else
    asm volatile("jmp *%0" : : "r"(pfn_timeGetDevCaps));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxytimeGetSystemTime(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_timeGetSystemTime;
#else
    asm volatile("jmp *%0" : : "r"(pfn_timeGetSystemTime));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxytimeGetTime(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_timeGetTime;
#else
    asm volatile("jmp *%0" : : "r"(pfn_timeGetTime));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxytimeKillEvent(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_timeKillEvent;
#else
    asm volatile("jmp *%0" : : "r"(pfn_timeKillEvent));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxytimeSetEvent(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_timeSetEvent;
#else
    asm volatile("jmp *%0" : : "r"(pfn_timeSetEvent));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxywaveInAddBuffer(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_waveInAddBuffer;
#else
    asm volatile("jmp *%0" : : "r"(pfn_waveInAddBuffer));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxywaveInClose(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_waveInClose;
#else
    asm volatile("jmp *%0" : : "r"(pfn_waveInClose));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxywaveInGetDevCapsA(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_waveInGetDevCapsA;
#else
    asm volatile("jmp *%0" : : "r"(pfn_waveInGetDevCapsA));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxywaveInGetDevCapsW(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_waveInGetDevCapsW;
#else
    asm volatile("jmp *%0" : : "r"(pfn_waveInGetDevCapsW));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxywaveInGetErrorTextA(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_waveInGetErrorTextA;
#else
    asm volatile("jmp *%0" : : "r"(pfn_waveInGetErrorTextA));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxywaveInGetErrorTextW(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_waveInGetErrorTextW;
#else
    asm volatile("jmp *%0" : : "r"(pfn_waveInGetErrorTextW));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxywaveInGetID(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_waveInGetID;
#else
    asm volatile("jmp *%0" : : "r"(pfn_waveInGetID));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxywaveInGetNumDevs(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_waveInGetNumDevs;
#else
    asm volatile("jmp *%0" : : "r"(pfn_waveInGetNumDevs));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxywaveInGetPosition(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_waveInGetPosition;
#else
    asm volatile("jmp *%0" : : "r"(pfn_waveInGetPosition));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxywaveInMessage(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_waveInMessage;
#else
    asm volatile("jmp *%0" : : "r"(pfn_waveInMessage));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxywaveInOpen(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_waveInOpen;
#else
    asm volatile("jmp *%0" : : "r"(pfn_waveInOpen));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxywaveInPrepareHeader(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_waveInPrepareHeader;
#else
    asm volatile("jmp *%0" : : "r"(pfn_waveInPrepareHeader));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxywaveInReset(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_waveInReset;
#else
    asm volatile("jmp *%0" : : "r"(pfn_waveInReset));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxywaveInStart(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_waveInStart;
#else
    asm volatile("jmp *%0" : : "r"(pfn_waveInStart));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxywaveInStop(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_waveInStop;
#else
    asm volatile("jmp *%0" : : "r"(pfn_waveInStop));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxywaveInUnprepareHeader(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_waveInUnprepareHeader;
#else
    asm volatile("jmp *%0" : : "r"(pfn_waveInUnprepareHeader));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxywaveOutBreakLoop(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_waveOutBreakLoop;
#else
    asm volatile("jmp *%0" : : "r"(pfn_waveOutBreakLoop));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxywaveOutClose(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_waveOutClose;
#else
    asm volatile("jmp *%0" : : "r"(pfn_waveOutClose));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxywaveOutGetDevCapsA(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_waveOutGetDevCapsA;
#else
    asm volatile("jmp *%0" : : "r"(pfn_waveOutGetDevCapsA));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxywaveOutGetDevCapsW(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_waveOutGetDevCapsW;
#else
    asm volatile("jmp *%0" : : "r"(pfn_waveOutGetDevCapsW));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxywaveOutGetErrorTextA(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_waveOutGetErrorTextA;
#else
    asm volatile("jmp *%0" : : "r"(pfn_waveOutGetErrorTextA));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxywaveOutGetErrorTextW(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_waveOutGetErrorTextW;
#else
    asm volatile("jmp *%0" : : "r"(pfn_waveOutGetErrorTextW));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxywaveOutGetID(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_waveOutGetID;
#else
    asm volatile("jmp *%0" : : "r"(pfn_waveOutGetID));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxywaveOutGetNumDevs(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_waveOutGetNumDevs;
#else
    asm volatile("jmp *%0" : : "r"(pfn_waveOutGetNumDevs));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxywaveOutGetPitch(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_waveOutGetPitch;
#else
    asm volatile("jmp *%0" : : "r"(pfn_waveOutGetPitch));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxywaveOutGetPlaybackRate(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_waveOutGetPlaybackRate;
#else
    asm volatile("jmp *%0" : : "r"(pfn_waveOutGetPlaybackRate));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxywaveOutGetPosition(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_waveOutGetPosition;
#else
    asm volatile("jmp *%0" : : "r"(pfn_waveOutGetPosition));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxywaveOutGetVolume(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_waveOutGetVolume;
#else
    asm volatile("jmp *%0" : : "r"(pfn_waveOutGetVolume));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxywaveOutMessage(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_waveOutMessage;
#else
    asm volatile("jmp *%0" : : "r"(pfn_waveOutMessage));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxywaveOutOpen(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_waveOutOpen;
#else
    asm volatile("jmp *%0" : : "r"(pfn_waveOutOpen));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxywaveOutPause(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_waveOutPause;
#else
    asm volatile("jmp *%0" : : "r"(pfn_waveOutPause));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxywaveOutPrepareHeader(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_waveOutPrepareHeader;
#else
    asm volatile("jmp *%0" : : "r"(pfn_waveOutPrepareHeader));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxywaveOutReset(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_waveOutReset;
#else
    asm volatile("jmp *%0" : : "r"(pfn_waveOutReset));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxywaveOutRestart(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_waveOutRestart;
#else
    asm volatile("jmp *%0" : : "r"(pfn_waveOutRestart));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxywaveOutSetPitch(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_waveOutSetPitch;
#else
    asm volatile("jmp *%0" : : "r"(pfn_waveOutSetPitch));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxywaveOutSetPlaybackRate(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_waveOutSetPlaybackRate;
#else
    asm volatile("jmp *%0" : : "r"(pfn_waveOutSetPlaybackRate));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxywaveOutSetVolume(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_waveOutSetVolume;
#else
    asm volatile("jmp *%0" : : "r"(pfn_waveOutSetVolume));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxywaveOutUnprepareHeader(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_waveOutUnprepareHeader;
#else
    asm volatile("jmp *%0" : : "r"(pfn_waveOutUnprepareHeader));
#endif
}

EXTERN_C __declspec(naked) void __cdecl proxywaveOutWrite(void)
{
#if defined(_MSC_VER)
    __asm jmp pfn_waveOutWrite;
#else
    asm volatile("jmp *%0" : : "r"(pfn_waveOutWrite));
#endif
}

